### ISSUE TITLE
Property instead of at-rule

### ISSUE THREAD

**Issue by ai** [jedmao/postcss-circle#1]
Maybe we should use property `circle` instead of at-rule? Because CSS semantic of at-rules is little bit different. Also property will be shorter.

Like:

``` css
.circle {
    circle: 100px red;
}
```

**Comment by jednano** [comment]
Thanks, @ai. I guess the reason I preferred this syntax is because I'm explicitly stating the `diameter` and `color` properties. This is, I believe, more readable. Do you have a solution that would allow me to keep named properties? I'm also interested in doing this for the purpose of sourcemapping back to the original declaration, where possible.

How about this?

``` css
.circle {
    circle: {
        diameter: 100px;
        color: red;
    }
}
```

Does that work? I realize, however, this looks exactly like the [`postcss-nested-props`](https://github.com/jedmao/postcss-nested-props#nested-properties) syntax.

**Comment by jednano** [comment]
The only other thing I can think of is like this:

``` css
.circle {
    shape: circle;
    diameter: 100px;
    color: red;
}
```

**Comment by ai** [comment]
`postcss-nested-props` syntax is totally miss CSS spirit :). So we should use it only in special cases.

What about shorcut and long versions like in `background`:

``` css
.one {
    circle-diameter: 100px;
    circle-color: red;
}
.two {
    circle: 100px red;
}
```

And we can use `postcss-nested-props` to write it in:

``` css
.one {
    circle: {
        diameter: 100px;
        color: red;
    }
}
```

**Comment by jednano** [comment]
Are you saying there should be a choice on how to define a circle and it would work both ways? I'm not sure I like choices.

See [choice is an anti-pattern](https://twitter.com/everzet/status/444045856900407296).

**Comment by ai** [comment]
I am totally agree that “choice is an anti-pattern” :). So like with `background`, `circle` is main property and should only used to override `circle-diameter`.

Or maybe we could wait for issue resolving, let’s collect other opinions.

**Comment by jednano** [comment]
That's true. I do like its consistency w/ the `background` property. Good point! What do you think about the `shape: circle` declaration? Then, I could add a triangle into the mix with `shape: triangle`.

**Comment by ai** [comment]
Yeap, it will be cool to have one plugins for few geometry forms. But maybe at-rule is better for `shape`, because it is easy to miss connection between properties (also `color`is for text color) in code like:

``` css
.circle {
    shape: circle;
    diameter: 100px;
    color: red;
}
```

**Comment by jednano** [comment]
@ai I agree with you. Fixed in https://github.com/jedmao/postcss-circle/commit/5306b11d513e24ff12ae5d73310595f6b85d1b47

**Comment by jednano** [comment]
@ai I think I can just remove the color at this point and just have:

``` css
.circle {
    circle: 100px;
    background-color: red;
}
```

That's about as simple as it gets.

BTW – you've expressed some of your philosophy here about what a PostCSS plugin should be and what it should not be. Have you thought about adding this philosophy to the [Plugin Guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md) so people have some guidance and less confusion?
