### ISSUE TITLE
Remove color property

### ISSUE THREAD

**Issue by jednano** [jedmao/postcss-circle#2]
Just let the color be defined by the `background-color` property. This mean the plugin will be as simple as this:

``` css
.circle {
    circle: 100px;
    background-color: red;
}
```
